---
- name: Create jupyterhub yaml file
  template: src=jupyterhub.j2 dest=/tmp/jupyterhub.yaml

- command: kubectl apply -f /tmp/jupyterhub.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Create jupyterhub yaml file
  command: 'kubectl create configmap jupyterhub --namespace=jupyterhub --from-file=/etc/jupyterhub_config.py --from-file=/etc/kubernetes/admin.conf'
  ignore_errors: yes
