---
- name: Create jupyterhub config file
  template: src=jupyterhub_config.py.j2 dest=/etc/jupyterhub_config.py

- name: Include "{{jupyterhub_spawner}}" tasks
  include: "{{jupyterhub_spawner}}.yaml"